### PR TITLE
Allow input of .NRRD file format

### PR DESCRIPTION
**Pull request by josesho**
Allows upload of skeletonised neuron in .NRRD file format via `dotprops` function

### CODE REVIEW

**Comment by jefferis** [comment]
Dear @josesho Jose,

Many thanks for your contribution. Very good idea!

I added various kinds of checks and documentation, and the patch is now merged to master.

Best,

Greg.

**Comment by josesho** [comment]
Hi Greg,

No problem, thanks for accepting the pull.

I tried uploading a .NRRD file of my own (Downsampled to 280 x 160 microns,
file size 48KB) , but got this error instead "cannot allocate vector of
size 187.0 Mb". Sounds like a restriction on your server side?

Joses

**Comment by jefferis** [comment]
The VPS is quite small and I also ran into this once. Have your tried a few times?

But if you raise an issue, I've thought of a way to reduce the memory usage further. Best,

Greg.

**Comment by jefferis** [comment]
re this:

> I tried uploading a .NRRD file of my own (Downsampled to 280 x 160 microns,
file size 48KB) , but got this error instead "cannot allocate vector of
size 187.0 Mb". Sounds like a restriction on your server side?

Just a couple comments: First, it is the uncompressed size that matters, and that is probably quite a bit bigger.

Also out of curiosity, if the image is downsampled then it should be the number of pixels rather than the number of microns that changes. Were you cropping (which is fine, of course if you change the origin appropriately, something that ImageJ/Fiji doesn't handle)?

**Comment by josesho** [comment]
Yes, uncompressed size is on the order of 100 MB. I am downsampling the
compressed file, and not the uncompressed version.

Secondly, both pixels and microns have changed, curiously, with no cropping
whatsoever.

Original --> 564.25 X 326.71 microns, 1769 X 1026 pixels
Downsampled --> 282.29 X 163.35 microns, 885 X 513 pixels

I simply use Plugins > Example > downsample. Or should I go about it a
different way?

On Wed, Aug 19, 2015 at 10:22 AM, Gregory Jefferis <notifications@github.com

**Comment by josesho** [comment]
You are right, the origin of the skeletonised neuron has been altered. 

screen shot 2015-08-19 at 3 03 45 pm

**Comment by jefferis** [comment]
OK, see https://groups.google.com/forum/#!topic/nat-user/qQo44Qi1TkM for my recommended pre-processing steps. Basically you cannot reliably crop in Fiji and you should use **Image ... Scale** not **Plugins ... Examples ... Downsample** since the latter does not set voxel size correctly (and only scales the XY dimensions).

**Pull request merged**
