### PR TITLE
Feature/neuron type

### PR DESCRIPTION
**Pull request by jefferis**
@ajdm can you take a look at this? It's still WIP as have not added to tracing upload results.

Also I started doing some refactoring to simplify code and maybe that should be a separate PR.

Also @mmc46 how would we get links to neuron classes on VFB based on this type information.

### CODE REVIEW

**Comment by ajdm** [comment]
> It's still WIP as have not added to tracing upload results.
Added in 2c83418bfa25553e8263fbdd69ccc45e1effdd6e.

**Comment by ajdm** [comment]
> It's still WIP as have not added to tracing upload results.

Added in 2c83418bfa25553e8263fbdd69ccc45e1effdd6e.

**Comment by ajdm** [comment]
> Also I started doing some refactoring to simplify code and maybe that should be a separate PR.

I noticed a few things that could be simplified while doing the last commit, so I think a separate PR would be good.

**Comment by jefferis** [comment]
Thanks @ajdm. Do you want to keep the directly relevant commits (eg git rebase --interactive) and then start another branch for the refactoring. Thanks! G.

**Comment by mmc46** [comment]
For the VFB links, there needs to be a mapping to the ontology id, if the link is for neuron class. 
The url would then be 

http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt:00110120

The mappings could potentially come from here, which is what we currently use to translate the LMB annotations to classes.

https://github.com/VirtualFlyBrain/VFB_owl/blob/master/doc/annotation_map.tsv

We could add another column with id

**Comment by jefferis** [comment]
> The mappings could potentially come from here, which is what we currently use to translate the LMB annotations to classes.
>
> https://github.com/VirtualFlyBrain/VFB_owl/blob/master/doc/annotation_map.tsv
>
> We could add another column with id

Thanks @mmc46. It would be great if you could add another column with the id. Then it would be easy to grab that file and use it to generate the VFB linkouts.

**Comment by mmc46** [comment]
The tsv file already has  an id column (class_id), scroll right.

https://github.com/VirtualFlyBrain/VFB_owl/blob/master/doc/annotation_map.tsv

**Comment by dosumis** [comment]
This report wasn't meant to be a reliable source for exporting our data.  As you may be using it, I'll try to keep it stable. 

The mapping in the annotation table (as reflected in the report linked to above) is prior to inference.  Details of how to get the mapping to types as seen on VFB are here #48

**Pull request closed without merging**
